/**
 * Classificador multi-sinal compartilhado (sync + backfill).
 *
 * Vocabulário CONTROLADO: só emite categorias da lista oficial (~22). Nunca usa
 * a tag crua como categoria. Avalia, em ordem de prioridade:
 *   1. Tags do manifest (dicionário keyword → categoria).
 *   2. Tokens de moniker / nome.
 *   3. Palavras-chave da descrição (match por palavra inteira).
 *   4. Heurística de publisher (publishers fortemente tipados).
 *
 * Um pacote pode receber múltiplas categorias. Se nada casar, retorna [] — sem
 * fallback "Outros"; o pacote continua buscável.
 */

export const CATEGORIES = [
  "developer-tools",
  "programming-languages",
  "productivity",
  "office-documents",
  "utilities",
  "system-drivers",
  "security-privacy",
  "networking",
  "multimedia",
  "audio-music",
  "video",
  "graphics-design",
  "photography",
  "games",
  "browsers",
  "communication",
  "social",
  "email",
  "cloud-storage",
  "file-management",
  "education",
  "terminal-shell",
] as const;

export type Category = (typeof CATEGORIES)[number];

export type LicenseGroup = "open-source" | "proprietary" | "unknown";

/**
 * Dicionário keyword → categorias. As chaves são normalizadas (minúsculas, só
 * alfanumérico) no momento do build. Mantenha keywords distintivas; evite termos
 * genéricos demais que gerariam falsos positivos (ex.: "app", "tool", "windows").
 */
const KEYWORDS: Record<Category, string[]> = {
  "developer-tools": [
    "developer-tools",
    "developer tools",
    "developer",
    "development",
    "devtools",
    "ide",
    "editor",
    "code editor",
    "code",
    "coding",
    "programming",
    "sdk",
    "api",
    "cli tool",
    "compiler",
    "build",
    "build-tools",
    "buildtools",
    "debugger",
    "debugging",
    "git",
    "github",
    "gitlab",
    "version control",
    "versioncontrol",
    "vcs",
    "source control",
    "devops",
    "ci",
    "cicd",
    "continuous integration",
    "docker",
    "kubernetes",
    "k8s",
    "container",
    "containers",
    "vagrant",
    "ansible",
    "terraform",
    "database",
    "databases",
    "sql client",
    "orm",
    "rest",
    "graphql",
    "framework",
    "library",
    "package manager",
    "packagemanager",
    "npm",
    "yarn",
    "pnpm",
    "maven",
    "gradle",
    "nuget",
    "pip",
    "composer",
    "vscode",
    "visual studio",
    "visualstudio",
    "jetbrains",
    "intellij",
    "pycharm",
    "webstorm",
    "eclipse",
    "netbeans",
    "android studio",
    "androidstudio",
    "xcode",
    "vim",
    "neovim",
    "emacs",
    "sublime",
    "atom",
    "notepad++",
    "notepadplusplus",
    "postman",
    "insomnia",
    "swagger",
    "regex",
    "json",
    "yaml",
    "xml",
    "linter",
    "formatter",
    "profiler",
    "emulator",
    "virtualization",
    "wsl",
    "mingw",
    "cygwin",
    "msys",
    "cmake",
    "make",
    "ninja",
    "bazel",
    "webpack",
    "vite",
    "babel",
    "eslint",
    "prettier",
    "unity",
    "unreal",
    "godot",
    "game engine",
    "gameengine",
  ],
  "programming-languages": [
    "programming language",
    "programminglanguage",
    "language runtime",
    "runtime",
    "interpreter",
    "python",
    "java",
    "jdk",
    "jre",
    "openjdk",
    "node",
    "nodejs",
    "node.js",
    "deno",
    "bun",
    "golang",
    "go lang",
    "rust",
    "rustlang",
    "cargo",
    "ruby",
    "perl",
    "php",
    "dotnet",
    ".net",
    "csharp",
    "c#",
    "fsharp",
    "f#",
    "cpp",
    "c++",
    "clang",
    "gcc",
    "kotlin",
    "scala",
    "clojure",
    "haskell",
    "elixir",
    "erlang",
    "lua",
    "julia",
    "dart",
    "flutter",
    "swift",
    "typescript",
    "javascript",
    "r language",
    "rlang",
    "fortran",
    "cobol",
    "pascal",
    "lisp",
    "ocaml",
    "groovy",
    "powershell language",
  ],
  productivity: [
    "productivity",
    "notes",
    "note-taking",
    "notetaking",
    "note taking",
    "todo",
    "task",
    "tasks",
    "task management",
    "to-do",
    "calendar",
    "planner",
    "planning",
    "organizer",
    "organization",
    "project management",
    "projectmanagement",
    "time tracking",
    "timetracking",
    "pomodoro",
    "kanban",
    "mind map",
    "mindmap",
    "knowledge base",
    "knowledgebase",
    "wiki",
    "outliner",
    "journal",
    "diary",
    "reminder",
    "reminders",
    "workflow",
    "automation",
    "macro",
    "clipboard",
    "snippet",
    "scheduling",
    "notion",
    "obsidian",
    "evernote",
    "onenote",
    "todoist",
    "trello",
    "asana",
  ],
  "office-documents": [
    "office",
    "office-suite",
    "officesuite",
    "document",
    "documents",
    "word processor",
    "wordprocessor",
    "spreadsheet",
    "spreadsheets",
    "presentation",
    "presentations",
    "slides",
    "pdf",
    "pdf reader",
    "pdfreader",
    "pdf editor",
    "ebook",
    "e-book",
    "epub",
    "reader",
    "writer",
    "latex",
    "markdown editor",
    "doc",
    "docx",
    "xlsx",
    "pptx",
    "libreoffice",
    "openoffice",
    "microsoft office",
    "microsoftoffice",
    "excel",
    "powerpoint",
    "onlyoffice",
    "wps office",
    "wpsoffice",
    "acrobat",
    "foxit",
    "sumatra",
    "calibre",
    "zotero",
    "mendeley",
  ],
  utilities: [
    "utility",
    "utilities",
    "system utility",
    "systemutility",
    "system tool",
    "tweak",
    "tweaks",
    "optimizer",
    "optimization",
    "cleaner",
    "cleanup",
    "uninstaller",
    "installer",
    "benchmark",
    "monitoring",
    "system monitor",
    "systemmonitor",
    "hardware",
    "diagnostics",
    "diagnostic",
    "backup",
    "restore",
    "disk",
    "partition",
    "defrag",
    "registry",
    "startup manager",
    "clipboard manager",
    "screenshot",
    "screen capture",
    "screencapture",
    "screen recorder",
    "screenrecorder",
    "color picker",
    "colorpicker",
    "calculator",
    "converter",
    "unit converter",
    "system information",
    "systeminformation",
    "task manager",
    "taskmanager",
    "power management",
    "battery",
    "keyboard",
    "mouse",
    "hotkey",
    "shortcut",
    "launcher",
    "search tool",
    "everything",
    "powertoys",
    "ccleaner",
    "rufus",
    "hwinfo",
    "cpu-z",
    "gpu-z",
    "crystaldiskinfo",
    "wiztree",
    "windirstat",
  ],
  "system-drivers": [
    "driver",
    "drivers",
    "device driver",
    "devicedriver",
    "firmware",
    "bios",
    "uefi",
    "chipset",
    "gpu driver",
    "graphics driver",
    "graphicsdriver",
    "printer driver",
    "audio driver",
    "network driver",
    "kernel",
    "system component",
    "redistributable",
    "runtime library",
    "vcredist",
    "visual c++ redistributable",
    "directx",
    "dotnet runtime",
    ".net runtime",
    "framework redistributable",
  ],
  "security-privacy": [
    "security",
    "privacy",
    "antivirus",
    "anti-virus",
    "anti virus",
    "antimalware",
    "anti-malware",
    "malware",
    "firewall",
    "encryption",
    "encrypt",
    "decrypt",
    "vpn",
    "password",
    "password manager",
    "passwordmanager",
    "2fa",
    "mfa",
    "authenticator",
    "two-factor",
    "twofactor",
    "secure",
    "cryptography",
    "crypto",
    "ssl",
    "tls",
    "certificate",
    "gpg",
    "pgp",
    "openssl",
    "veracrypt",
    "bitwarden",
    "keepass",
    "1password",
    "lastpass",
    "tor",
    "wireguard",
    "openvpn",
    "yubikey",
    "penetration testing",
    "pentest",
    "vulnerability",
    "sandbox security",
  ],
  networking: [
    "network",
    "networking",
    "ssh",
    "sftp",
    "ftp",
    "ftp client",
    "ftpclient",
    "telnet",
    "remote desktop",
    "remotedesktop",
    "rdp",
    "remote access",
    "remoteaccess",
    "proxy",
    "dns",
    "dhcp",
    "router",
    "packet",
    "wireshark",
    "nmap",
    "ping",
    "traceroute",
    "bandwidth",
    "wifi",
    "wi-fi",
    "ethernet",
    "tcp",
    "udp",
    "http server",
    "web server",
    "webserver",
    "nginx",
    "apache server",
    "tunnel",
    "ngrok",
    "putty",
    "winscp",
    "filezilla",
    "mobaxterm",
    "teamviewer",
    "anydesk",
    "tailscale",
  ],
  multimedia: [
    "multimedia",
    "media",
    "media player",
    "mediaplayer",
    "codec",
    "codecs",
    "streaming",
    "podcast",
    "karaoke",
    "dlna",
    "media center",
    "mediacenter",
    "media server",
    "mediaserver",
    "plex",
    "kodi",
    "jellyfin",
  ],
  "audio-music": [
    "audio",
    "music",
    "music player",
    "musicplayer",
    "sound",
    "audio editor",
    "audioeditor",
    "daw",
    "digital audio workstation",
    "mixing",
    "mastering",
    "synthesizer",
    "synth",
    "midi",
    "vst",
    "audio recorder",
    "voice recorder",
    "voicerecorder",
    "equalizer",
    "mp3",
    "flac",
    "spotify",
    "audacity",
    "foobar2000",
    "fl studio",
    "flstudio",
    "ableton",
    "reaper",
    "musicbee",
    "winamp",
    "soundtrack",
    "radio",
  ],
  video: [
    "video",
    "video player",
    "videoplayer",
    "video editor",
    "videoeditor",
    "video editing",
    "movie",
    "movies",
    "film",
    "screencast",
    "vlog",
    "video converter",
    "videoconverter",
    "transcoding",
    "encoder",
    "h264",
    "h265",
    "hevc",
    "mkv",
    "mp4",
    "subtitle",
    "subtitles",
    "vlc",
    "obs",
    "obs studio",
    "obsstudio",
    "handbrake",
    "davinci resolve",
    "davinciresolve",
    "shotcut",
    "kdenlive",
    "premiere",
    "potplayer",
    "mpc-hc",
    "youtube downloader",
    "streaming video",
  ],
  "graphics-design": [
    "graphics",
    "graphic design",
    "graphicdesign",
    "design",
    "image editor",
    "imageeditor",
    "image editing",
    "vector",
    "vector graphics",
    "illustration",
    "drawing",
    "painting",
    "digital art",
    "digitalart",
    "3d",
    "3d modeling",
    "3dmodeling",
    "modeling",
    "rendering",
    "render",
    "cad",
    "animation",
    "ui design",
    "uidesign",
    "ux",
    "prototyping",
    "icon",
    "icons",
    "wallpaper",
    "photoshop",
    "illustrator",
    "gimp",
    "inkscape",
    "krita",
    "blender",
    "figma",
    "sketch",
    "affinity",
    "coreldraw",
    "paint.net",
    "paintnet",
    "fontforge",
    "fonts",
    "typography",
  ],
  photography: [
    "photography",
    "photo",
    "photos",
    "photo editor",
    "photoeditor",
    "photo editing",
    "raw",
    "raw editor",
    "lightroom",
    "darktable",
    "rawtherapee",
    "camera",
    "exif",
    "photo manager",
    "photomanager",
    "image viewer",
    "imageviewer",
    "photo viewer",
    "photoviewer",
    "irfanview",
    "xnview",
    "digikam",
    "faststone",
  ],
  games: [
    "game",
    "games",
    "gaming",
    "gamer",
    "game launcher",
    "gamelauncher",
    "game client",
    "gameclient",
    "emulator game",
    "retroarch",
    "steam",
    "epic games",
    "epicgames",
    "gog",
    "origin",
    "uplay",
    "ubisoft connect",
    "battle.net",
    "battlenet",
    "ea app",
    "playnite",
    "minecraft",
    "roblox",
    "discord game",
    "mod manager",
    "modmanager",
    "game mod",
    "cheat engine",
    "cheatengine",
    "controller",
    "gamepad",
    "joystick",
    "speedrun",
  ],
  browsers: [
    "browser",
    "browsers",
    "web browser",
    "webbrowser",
    "chromium",
    "chrome",
    "firefox",
    "edge",
    "opera",
    "brave",
    "vivaldi",
    "safari",
    "tor browser",
    "torbrowser",
    "waterfox",
    "librewolf",
    "browser extension",
  ],
  communication: [
    "communication",
    "messaging",
    "messenger",
    "chat",
    "instant messaging",
    "instantmessaging",
    "voip",
    "video call",
    "videocall",
    "video conferencing",
    "videoconferencing",
    "conferencing",
    "voice chat",
    "voicechat",
    "telephony",
    "sms",
    "irc",
    "xmpp",
    "matrix chat",
    "discord",
    "slack",
    "telegram",
    "whatsapp",
    "signal",
    "zoom",
    "skype",
    "microsoft teams",
    "microsoftteams",
    "teams",
    "webex",
    "mumble",
    "teamspeak",
  ],
  social: [
    "social",
    "social media",
    "socialmedia",
    "social network",
    "socialnetwork",
    "twitter",
    "x app",
    "mastodon",
    "reddit",
    "facebook",
    "instagram",
    "tiktok",
    "linkedin",
    "tumblr",
    "bluesky",
    "fediverse",
  ],
  email: [
    "email",
    "e-mail",
    "mail",
    "mail client",
    "mailclient",
    "email client",
    "emailclient",
    "webmail",
    "imap",
    "smtp",
    "pop3",
    "newsletter",
    "outlook",
    "thunderbird",
    "mailspring",
    "gmail",
    "protonmail",
    "proton mail",
    "em client",
    "emclient",
    "mailbird",
  ],
  "cloud-storage": [
    "cloud storage",
    "cloudstorage",
    "cloud",
    "cloud sync",
    "cloudsync",
    "file sync",
    "filesync",
    "sync client",
    "syncclient",
    "online storage",
    "object storage",
    "dropbox",
    "google drive",
    "googledrive",
    "onedrive",
    "nextcloud",
    "owncloud",
    "mega",
    "box",
    "icloud",
    "pcloud",
    "s3",
    "backblaze",
    "rclone",
    "syncthing",
  ],
  "file-management": [
    "file manager",
    "filemanager",
    "file management",
    "filemanagement",
    "file explorer",
    "fileexplorer",
    "archive",
    "archiver",
    "compression",
    "compress",
    "zip",
    "unzip",
    "rar",
    "7zip",
    "7-zip",
    "winrar",
    "winzip",
    "extract",
    "file transfer",
    "filetransfer",
    "file renamer",
    "duplicate finder",
    "duplicatefinder",
    "file search",
    "tar",
    "gzip",
    "peazip",
    "bandizip",
    "nanazip",
    "total commander",
    "totalcommander",
    "filemenu",
  ],
  education: [
    "education",
    "educational",
    "learning",
    "e-learning",
    "elearning",
    "course",
    "courses",
    "tutorial",
    "study",
    "flashcard",
    "flashcards",
    "anki",
    "language learning",
    "languagelearning",
    "dictionary",
    "encyclopedia",
    "reference",
    "math",
    "mathematics",
    "science",
    "astronomy",
    "geography",
    "typing tutor",
    "typingtutor",
    "school",
    "academic",
    "research",
    "stellarium",
    "geogebra",
  ],
  "terminal-shell": [
    "terminal",
    "shell",
    "console",
    "command line",
    "commandline",
    "command-line",
    "command prompt",
    "commandprompt",
    "bash",
    "zsh",
    "fish shell",
    "powershell",
    "pwsh",
    "tmux",
    "screen multiplexer",
    "prompt",
    "windows terminal",
    "windowsterminal",
    "alacritty",
    "wezterm",
    "kitty terminal",
    "hyper terminal",
    "cmder",
    "conemu",
    "starship",
    "oh-my-posh",
    "ohmyposh",
    "oh-my-zsh",
  ],
};

/**
 * Heurística de publisher → categoria. Só publishers fortemente associados a uma
 * categoria. Chaves normalizadas; match por substring no publisher normalizado.
 */
const PUBLISHER_HINTS: Array<{ match: string; categories: Category[] }> = [
  { match: "valve", categories: ["games"] },
  { match: "epic games", categories: ["games"] },
  { match: "ubisoft", categories: ["games"] },
  { match: "electronic arts", categories: ["games"] },
  { match: "blizzard", categories: ["games"] },
  { match: "activision", categories: ["games"] },
  { match: "riot games", categories: ["games"] },
  { match: "rockstar games", categories: ["games"] },
  { match: "cd projekt", categories: ["games"] },
  { match: "bethesda", categories: ["games"] },
  { match: "square enix", categories: ["games"] },
  { match: "bandai namco", categories: ["games"] },
  { match: "sega", categories: ["games"] },
  { match: "capcom", categories: ["games"] },
  { match: "gog", categories: ["games"] },
  { match: "mozilla", categories: ["browsers"] },
  { match: "brave software", categories: ["browsers"] },
  { match: "vivaldi", categories: ["browsers"] },
  { match: "opera", categories: ["browsers"] },
  { match: "jetbrains", categories: ["developer-tools"] },
  { match: "gitkraken", categories: ["developer-tools"] },
  { match: "docker", categories: ["developer-tools"] },
  { match: "hashicorp", categories: ["developer-tools"] },
  { match: "postman", categories: ["developer-tools"] },
  { match: "adobe", categories: ["graphics-design"] },
  { match: "corel", categories: ["graphics-design"] },
  { match: "blender foundation", categories: ["graphics-design"] },
  { match: "autodesk", categories: ["graphics-design"] },
  { match: "the document foundation", categories: ["office-documents"] },
  { match: "foxit", categories: ["office-documents"] },
  { match: "nitro software", categories: ["office-documents"] },
  { match: "nordvpn", categories: ["security-privacy"] },
  { match: "proton ag", categories: ["security-privacy"] },
  { match: "bitwarden", categories: ["security-privacy"] },
  { match: "agilebits", categories: ["security-privacy"] },
  { match: "malwarebytes", categories: ["security-privacy"] },
  { match: "eset", categories: ["security-privacy"] },
  { match: "kaspersky", categories: ["security-privacy"] },
  { match: "bitdefender", categories: ["security-privacy"] },
  { match: "avast", categories: ["security-privacy"] },
  { match: "avg technologies", categories: ["security-privacy"] },
  { match: "spotify", categories: ["audio-music"] },
  { match: "discord inc", categories: ["communication"] },
  { match: "slack technologies", categories: ["communication"] },
  { match: "telegram", categories: ["communication"] },
  { match: "videolan", categories: ["video"] },
];

/** Normaliza para a forma compacta usada como chave do índice (alfanumérico). */
function compact(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "");
}

/** Índice keyword-compacta → categorias (construído uma vez). */
const KEYWORD_INDEX: Map<string, Category[]> = (() => {
  const index = new Map<string, Category[]>();
  for (const category of CATEGORIES) {
    for (const keyword of KEYWORDS[category]) {
      const key = compact(keyword);
      if (!key) continue;
      const existing = index.get(key);
      if (existing) {
        if (!existing.includes(category)) existing.push(category);
      } else {
        index.set(key, [category]);
      }
    }
  }
  return index;
})();

/**
 * Keywords legíveis (forma original, minúscula) com >= 3 chars, usadas para
 * match por palavra inteira na descrição.
 */
const DESCRIPTION_TERMS: Array<{ regex: RegExp; categories: Category[] }> = (() => {
  const seen = new Map<string, Category[]>();
  for (const category of CATEGORIES) {
    for (const keyword of KEYWORDS[category]) {
      const term = keyword.toLowerCase().trim();
      if (term.length < 3) continue;
      const existing = seen.get(term);
      if (existing) {
        if (!existing.includes(category)) existing.push(category);
      } else {
        seen.set(term, [category]);
      }
    }
  }
  return Array.from(seen.entries()).map(([term, categories]) => {
    const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return { regex: new RegExp(`(?:^|[^a-z0-9])${escaped}(?:$|[^a-z0-9])`, "i"), categories };
  });
})();

function addAll(target: Set<Category>, categories: Category[]): void {
  for (const category of categories) target.add(category);
}

function tokenize(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
}

export function classifyCategories(input: {
  tags?: string[];
  name?: string;
  moniker?: string | null;
  description?: string | null;
  publisher?: string | null;
}): string[] {
  const result = new Set<Category>();

  // 1. Tags — sinal mais forte. Tenta a tag inteira (compacta) e seus tokens.
  if (Array.isArray(input.tags)) {
    for (const tag of input.tags) {
      if (typeof tag !== "string") continue;
      const whole = KEYWORD_INDEX.get(compact(tag));
      if (whole) addAll(result, whole);
      for (const token of tokenize(tag)) {
        const hit = KEYWORD_INDEX.get(token);
        if (hit) addAll(result, hit);
      }
    }
  }

  // 2. Moniker / nome — tokens.
  for (const source of [input.moniker, input.name]) {
    if (!source) continue;
    for (const token of tokenize(source)) {
      const hit = KEYWORD_INDEX.get(token);
      if (hit) addAll(result, hit);
    }
  }

  // 3. Descrição — palavras inteiras (mais ruidoso, então roda só se necessário
  //    para aumentar cobertura, mas sempre acrescenta sinais válidos).
  if (input.description) {
    const desc = input.description.toLowerCase();
    for (const { regex, categories } of DESCRIPTION_TERMS) {
      if (regex.test(desc)) addAll(result, categories);
    }
  }

  // 4. Heurística de publisher.
  if (input.publisher) {
    const pub = input.publisher.toLowerCase();
    for (const hint of PUBLISHER_HINTS) {
      if (pub.includes(hint.match)) addAll(result, hint.categories);
    }
  }

  return Array.from(result);
}

const OPEN_SOURCE_PATTERNS: RegExp[] = [
  /\bmit\b/,
  /\bgpl\b/,
  /gnu general public/,
  /\blgpl\b/,
  /\bagpl\b/,
  /lesser general public/,
  /affero/,
  /apache/,
  /\bbsd\b/,
  /\bmpl\b/,
  /mozilla public/,
  /\bisc\b/,
  /\bzlib\b/,
  /unlicense/,
  /\bcc0\b/,
  /eclipse public/,
  /\bepl\b/,
  /artistic license/,
  /\bofl\b/,
  /open font license/,
  /\bwtfpl\b/,
  /\bcddl\b/,
  /boost software/,
  /public domain/,
  /open[\s-]?source/,
  /\bgnu\b/,
  /\bgplv[23]\b/,
  /\bgpl-[23]/,
  /\bsil\b/,
];

const PROPRIETARY_PATTERNS: RegExp[] = [
  /proprietary/,
  /commercial/,
  /\beula\b/,
  /freeware/,
  /shareware/,
  /trialware/,
  /all rights reserved/,
  /closed[\s-]?source/,
  /end user license/,
  /\bpaid\b/,
];

export function classifyLicenseGroup(
  license: string | null | undefined,
): LicenseGroup {
  if (!license) return "unknown";
  const value = license.toLowerCase().trim();
  if (!value) return "unknown";

  for (const pattern of OPEN_SOURCE_PATTERNS) {
    if (pattern.test(value)) return "open-source";
  }
  for (const pattern of PROPRIETARY_PATTERNS) {
    if (pattern.test(value)) return "proprietary";
  }
  return "unknown";
}
